In [28]:
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt 
import statsmodels.api as sm
from statsmodels.formula.api import ols
import datetime

In [29]:
import plotly.express as px
import pandas as pd

df = pd.read_csv("location_coordinate.csv")

fig = px.scatter_geo(df,lat='lat',lon='long', hover_name="id")
fig.update_layout(title = 'France', title_x=0.5)
fig.show()

FileNotFoundError: [Errno 2] No such file or directory: 'location_coordinate.csv'

In [25]:
import pandas as pd
from shapely.geometry import Point
import geopandas as gpd
from geopandas import GeoDataFrame
from geopy.geocoders import Nominatim

In [31]:
#postal code to GPS 
geolocator = Nominatim(user_agent="my-app")

def zip_to_lat(zip):

    location = geolocator.geocode({"postalcode": "38160", "country": "France"})
    lat = location.latitude
    

    return(lat)

def zip_to_long(zip):

In [27]:
lat

45.15548858373983

In [2]:
df_A=pd.read_csv("/Users/corentinpla/Documents/C-2-Statap/transactions_A.csv")
df_B=pd.read_csv("/Users/corentinpla/Documents/C-2-Statap/transactions_B.csv")

In [3]:
df_concat=pd.concat([df_A,df_B])

In [13]:
df_concat.head()

,tx_id,sender_account_id,receiver_account_id,tx_amount,timestamp,tx_type,sender_bank_id,sender_first_name,sender_last_name,sender_country_code,sender_birth_date,sender_zip_code,receiver_bank_id,receiver_first_name,receiver_last_name,receiver_country_code,receiver_birth_date,receiver_zip_code,is_alert_solo,is_alert_pooled
0,3109,6822.0,NaN,229.97,2018-03-03,WIRE,A,Marie,Lee,FR,1937-08-23,27800,C,Maritn,Alvarez,FR,1930-08-29,89160,False,False
1,1829,NaN,9011.0,117.83,2018-03-03,WIRE,B,Kurt,Brignac,FR,1962-09-07,35660,A,Joseph,Gable,FR,1933-12-23,62116,False,False
2,1830,NaN,7140.0,117.83,2018-03-03,WIRE,B,Kurt,Brignac,FR,1962-09-07,35660,A,Shelley,Spencer,FR,1944-12-23,34360,False,False
3,1831,NaN,1822.0,526.02,2018-03-03,WIRE,C,Shelly,Jethva,CN,1961-06-29,65230,A,Ambrose,Cole,FR,1958-04-07,3800,False,False
4,1832,5390.0,NaN,35.79,2018-03-03,WIRE,A,Judy,James,FR,1942-04-08,42140,C,Jose,Fiume,FR,1981-08-28,66820,False,False

In [14]:
df_is_alert=df_concat[df_concat["is_alert_pooled"]==True]

In [20]:
df_is_alert.groupby("receiver_country_code").count()

,tx_id,sender_account_id,receiver_account_id,tx_amount,timestamp,tx_type,sender_bank_id,sender_first_name,sender_last_name,sender_country_code,sender_birth_date,sender_zip_code,receiver_bank_id,receiver_first_name,receiver_last_name,receiver_birth_date,receiver_zip_code,is_alert_solo,is_alert_pooled
receiver_country_code,,,,,,,,,,,,,,,,,,,
AT,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
BR,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
CA,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
CD,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
CN,7,7,0,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
CO,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
EG,5,5,0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
ET,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
FR,1587,941,977,1587,1587,1587,1587,1587,1587,1587,1587,1587,1587,1587,1587,1587,1587,1587,1587
GB,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ID,3,3,0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
IN,8,8,0,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
MX,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MY,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
PK,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
RU,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
TH,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
US,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2

In [ ]:
#Analyse spatiale